 middle of throwing an exception, so
// we cannot let this exception go unhandle