ception &e)
    {
	cerr << "ERROR -- caught exception: " << 